version: "3"

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: not_very_secret

    volumes:
      - mariadb_data:/var/lib/mariadb

  web:
    image: nginx:latest
    ports: 
      - 8000:80

    volumes:
      - ${nginx_conf}:/etc/nginx/conf.d/default.conf
      - ${app_dir}:/app

    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile

    volumes:
      - ${app_dir}:/app
      - ./php-conf/debug.conf:/usr/local/etc/php-fpm.d/debug.conf

    depends_on:
      - mariadb
        
  phpmyadmin:
    image: phpmyadmin:latest

    ports:
      - 8100:80

    links:
      - mariadb:db

    depends_on:
      - mariadb

volumes:
  mariadb_data: {}
